### ISSUE TITLE
Suggestion: Support for Tips mod

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Loading-Progress-Bar#1]
The [Tips](https://www.curseforge.com/minecraft/mc-mods/tips) mod gets overwritten by Loading Progress Bar.
If possible, it would be really cool if those two worked together.

**Comment by jbredwards** [comment]
works fine for me

**Comment by jbredwards** [comment]
do the tips also not render without this mod installed? This mod doesn't override the screen renderer and doesn't add/change/remove any rendering code in general, just changes a hardcoded -1 returned loading progress to use the same value mc already prints to the console

**Comment by juraj-hrivnak** [comment]
Oh, yeah, it does work. I don't know why I remembered it doesn't, sorry about that. 
It's really great and simple mod!
